/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author HDS
 */
public class VSTeacher extends javax.swing.JFrame {

    /**
     * Creates new form VSProfesore
     */
    public VSTeacher() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        PanelP = new javax.swing.JPanel();
        Panel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2sec = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx2nalum = new javax.swing.JTextField();
        btn2lim = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn2adm = new javax.swing.JButton();
        tx2nom = new javax.swing.JTextField();
        tx2id = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn2bus = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tx2nom1 = new javax.swing.JTextField();
        Panel2 = new javax.swing.JPanel();
        txtext12 = new javax.swing.JLabel();
        txtext13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtext14 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txcodp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txnomp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txapep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txdni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtel = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txdir = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txema = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btngcam = new javax.swing.JButton();
        btncand = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Panel0 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 0, 0));
        titulo1.setText("PORTAL DEL PROFESOR");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 0, 204));
        btn3.setText("EXAMEN");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 40));

        btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 0, 204));
        btn2.setText("CURSOS");
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 0, 204));
        btn1.setText("PERFIL");
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("Acciones");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 520));

        PanelP.setBackground(new java.awt.Color(255, 255, 255));
        PanelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel3.setName("Panel3"); // NOI18N
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Cursos a cargo");
        Panel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 20));

        tabla2sec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla2sec);

        Panel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 440, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel2.setText("Nombre Grupo:");

        btn2lim.setText("Limpiar");

        jLabel14.setText("Numero de alumnos:");

        btn2adm.setText("Administrar");

        jLabel17.setText("Código:");

        btn2bus.setText("BUS");

        jLabel15.setText("Nombre Curso:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn2adm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btn2lim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tx2id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn2bus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx2nalum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx2nom)))))
                .addGap(16, 16, 16))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx2nom1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tx2id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2bus))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx2nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tx2nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tx2nalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2adm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2lim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        Panel3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 290, 300));

        PanelP.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.setName("Panel2"); // NOI18N
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtext12.setBackground(new java.awt.Color(204, 255, 255));
        txtext12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtext12.setForeground(new java.awt.Color(0, 153, 51));
        txtext12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtext12.setText("Generación de examen");
        Panel2.add(txtext12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 300, 40));

        txtext13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtext13.setForeground(new java.awt.Color(0, 153, 153));
        txtext13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtext13.setText("Personalizado");
        Panel2.add(txtext13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, 40));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/examen.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, 160));

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/examen.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 160));

        txtext14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtext14.setForeground(new java.awt.Color(0, 153, 153));
        txtext14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtext14.setText("Automatico");
        Panel2.add(txtext14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, 40));

        PanelP.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel1.setName("Panel1"); // NOI18N
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_96px_2.png"))); // NOI18N
        Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txcodp.setBorder(null);
        Panel1.add(txcodp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 220, 30));
        Panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 220, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Código de Profesor");
        Panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        Panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, 10));

        txnomp.setBorder(null);
        Panel1.add(txnomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Nombres:");
        Panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));
        Panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 10));

        txapep.setBorder(null);
        Panel1.add(txapep, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Apellidos:");
        Panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        Panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 220, 10));

        txdni.setBorder(null);
        Panel1.add(txdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("DNI:");
        Panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Telefono/Celular");
        Panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtel.setBorder(null);
        Panel1.add(txtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, 30));
        Panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("Dirección:");
        Panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        txdir.setBorder(null);
        Panel1.add(txdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 360, 30));
        Panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 360, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Email:");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txema.setBorder(null);
        Panel1.add(txema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 280, 30));
        Panel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 280, 10));

        btngcam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btngcam.setForeground(new java.awt.Color(0, 153, 0));
        btngcam.setText("Guardar Cambios");
        btngcam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel1.add(btngcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 150, 40));

        btncand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncand.setForeground(new java.awt.Color(0, 153, 0));
        btncand.setText("Cancelar");
        btncand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel1.add(btncand, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 90, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Datos Personales");
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 160, 20));

        PanelP.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel0.setBackground(new java.awt.Color(153, 255, 255));
        Panel0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel0.setName("Panel2"); // NOI18N
        Panel0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-profesor.png"))); // NOI18N
        Panel0.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, 150));

        titulo2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(0, 153, 153));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Bienvenido profesor");
        Panel0.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 710, 40));

        PanelP.add(Panel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        getContentPane().add(PanelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel0;
    public javax.swing.JPanel Panel1;
    public javax.swing.JPanel Panel2;
    public javax.swing.JPanel Panel3;
    public javax.swing.JPanel PanelP;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn2adm;
    public javax.swing.JButton btn2bus;
    public javax.swing.JButton btn2lim;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btncand;
    public javax.swing.JButton btngcam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTable tabla2sec;
    private javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JTextField tx2id;
    public javax.swing.JTextField tx2nalum;
    public javax.swing.JTextField tx2nom;
    public javax.swing.JTextField tx2nom1;
    public javax.swing.JTextField txapep;
    public javax.swing.JTextField txcodp;
    public javax.swing.JTextField txdir;
    public javax.swing.JTextField txdni;
    public javax.swing.JTextField txema;
    public javax.swing.JTextField txnomp;
    public javax.swing.JTextField txtel;
    public javax.swing.JLabel txtext12;
    public javax.swing.JLabel txtext13;
    public javax.swing.JLabel txtext14;
    // End of variables declaration//GEN-END:variables
}
