/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author HDS
 */
public class VSTeacher extends javax.swing.JFrame {

    /**
     * Creates new form VSProfesore
     */
    public VSTeacher() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnexa = new javax.swing.JButton();
        btncur = new javax.swing.JButton();
        btnper = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        Panel0 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txcodp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txnomp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txapep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txdni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtel = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txdir = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txema = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btngcam = new javax.swing.JButton();
        btncand = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtext12 = new javax.swing.JLabel();
        txtext13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacur = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txnomg = new javax.swing.JTextField();
        btndes = new javax.swing.JButton();
        btnlims = new javax.swing.JButton();
        btnads = new javax.swing.JButton();
        btnups = new javax.swing.JButton();
        cbsub = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnadms = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txidg = new javax.swing.JTextField();
        btnbuss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 0, 0));
        titulo1.setText("PORTAL DEL PROFESOR");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnexa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnexa.setForeground(new java.awt.Color(0, 153, 0));
        btnexa.setText("EXAMEN");
        jPanel2.add(btnexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 40));

        btncur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncur.setForeground(new java.awt.Color(0, 153, 0));
        btncur.setText("CURSOS");
        jPanel2.add(btncur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 40));

        btnper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnper.setForeground(new java.awt.Color(0, 153, 0));
        btnper.setText("PERFIL");
        jPanel2.add(btnper, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Acciones");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 520));

        rSPanelsSlider1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel0.setBackground(new java.awt.Color(153, 255, 255));
        Panel0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel0.setName("Panel2"); // NOI18N
        Panel0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-profesor.png"))); // NOI18N
        Panel0.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, 150));

        titulo2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(0, 153, 153));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Bienvenido profesor");
        Panel0.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 710, 40));

        rSPanelsSlider1.add(Panel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel1.setName("Panel1"); // NOI18N
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_96px_2.png"))); // NOI18N
        Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txcodp.setBorder(null);
        Panel1.add(txcodp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 220, 30));
        Panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 220, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Código de Profesor");
        Panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        Panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, 10));

        txnomp.setBorder(null);
        Panel1.add(txnomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Nombres:");
        Panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));
        Panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 10));

        txapep.setBorder(null);
        Panel1.add(txapep, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Apellidos:");
        Panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        Panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 220, 10));

        txdni.setBorder(null);
        Panel1.add(txdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("DNI:");
        Panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Telefono/Celular");
        Panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtel.setBorder(null);
        Panel1.add(txtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, 30));
        Panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("Dirección:");
        Panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        txdir.setBorder(null);
        Panel1.add(txdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 360, 30));
        Panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 360, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Email:");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txema.setBorder(null);
        Panel1.add(txema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 280, 30));
        Panel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 280, 10));

        btngcam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btngcam.setForeground(new java.awt.Color(0, 153, 0));
        btngcam.setText("Guardar Cambios");
        btngcam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel1.add(btngcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 150, 40));

        btncand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncand.setForeground(new java.awt.Color(0, 153, 0));
        btncand.setText("Cancelar");
        btncand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel1.add(btncand, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 90, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Datos Personales");
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 160, 20));

        rSPanelsSlider1.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.setName("Panel2"); // NOI18N
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-profesor.png"))); // NOI18N
        Panel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 150));

        txtext12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtext12.setForeground(new java.awt.Color(0, 153, 153));
        txtext12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtext12.setText("Generar examen automatico");
        Panel2.add(txtext12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 360, 40));

        txtext13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtext13.setForeground(new java.awt.Color(0, 153, 153));
        txtext13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtext13.setText("Generar examen manual");
        Panel2.add(txtext13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 310, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-profesor.png"))); // NOI18N
        Panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 150, 150));

        rSPanelsSlider1.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel3.setName("Panel3"); // NOI18N
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Cursos a cargo");
        Panel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 20));

        tablacur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablacur);

        Panel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 420, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel2.setText("Nombre Grupo:");

        btndes.setText("Eliminar");

        btnlims.setText("Limpiar");

        btnads.setText("Agregar");

        btnups.setText("Modificar");

        cbsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel14.setText("Curso:");

        btnadms.setText("Administrar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txnomg))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbsub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnups)
                    .addComponent(btnads))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlims, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnadms)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txnomg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnads)
                    .addComponent(btndes))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnups)
                    .addComponent(btnlims))
                .addGap(18, 18, 18)
                .addComponent(btnadms)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 280, 250));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel17.setText("Código:");

        btnbuss.setText("BUS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txidg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnbuss)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txidg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuss))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Panel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, 90));

        rSPanelsSlider1.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel0;
    public javax.swing.JPanel Panel1;
    public javax.swing.JPanel Panel2;
    public javax.swing.JPanel Panel3;
    public javax.swing.JButton btnadms;
    public javax.swing.JButton btnads;
    public javax.swing.JButton btnbuss;
    public javax.swing.JButton btncand;
    public javax.swing.JButton btncur;
    public javax.swing.JButton btndes;
    public javax.swing.JButton btnexa;
    public javax.swing.JButton btngcam;
    public javax.swing.JButton btnlims;
    public javax.swing.JButton btnper;
    public javax.swing.JButton btnups;
    public javax.swing.JComboBox<String> cbsub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public rojerusan.RSPanelsSlider rSPanelsSlider1;
    public javax.swing.JTable tablacur;
    private javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JTextField txapep;
    public javax.swing.JTextField txcodp;
    public javax.swing.JTextField txdir;
    public javax.swing.JTextField txdni;
    public javax.swing.JTextField txema;
    public javax.swing.JTextField txidg;
    public javax.swing.JTextField txnomg;
    public javax.swing.JTextField txnomp;
    public javax.swing.JTextField txtel;
    public javax.swing.JLabel txtext12;
    public javax.swing.JLabel txtext13;
    // End of variables declaration//GEN-END:variables
}
